### ISSUE TITLE
Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

### ISSUE THREAD

**Issue by rumes** [OzanKurt/Repoist#11]
When I using with laravel 5.4 after running  

`php artisan vendor:publish`

it give Error

`[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found`

**Comment by OzanKurt** [comment]
Haven't updated to 5.4, I will create a new release for that soon.
