### ISSUE TITLE
Trouple with working Laravel 5.4 . Please update it !

### ISSUE THREAD

**Issue by akkerise** [OzanKurt/Repoist#12]
I'm really having a lot of trouble with your package. When it is not compatible with version 5.4, I would like you to be able to update with this change! Thank you very much !

**Comment by egonvb** [comment]
To be more precise, laravel 5.4 returns following error: 

[Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'Illuminate\Console\AppNamespaceDetectorTrait' not found

**Comment by MarlonEtiene** [comment]
Same problem here

**Comment by insign** [comment]
![image](https://user-images.githubusercontent.com/1113045/27880069-13bc46e6-619a-11e7-98b6-c591de67c4ec.png)

**Comment by pastrikosko-zz** [comment]
same here...looks like that trait has been removed from 5.4..

**Comment by achinthas** [comment]
same here for 5.5

**Comment by insign** [comment]
Looks abandoned

**Comment by OzanKurt** [comment]
Currently working on the update. Thanks for your interest.
