### ISSUE TITLE
Default namespaces

### ISSUE THREAD

**Issue by mattsims** [OzanKurt/Repoist#20]
Would it make sense to prefix the default namespaces that are published in the vendor config with `App\`? So something like this:
```
	'namespaces' => [
	    'contracts' => 'App\Repositories\Contracts',
	    'repositories' => 'App\Repositories\Eloquent',
	],
```
Happy to submit a PR if that makes sense :+1:

**Comment by OzanKurt** [comment]
You know Laravel has a command called `php artisan app:name` to set a requested base namespace for your application. The package is already using it.

You can have a look at the command `MakeRepositoryCommand`, at line 154:
```php
$this->laravel->getNamespace()
```
is being used to get that.

Please let me know about your thoughts.

**Edit:** 
I just noticed that the namespace is not there. 😊
I will be fixing that asap.

**Comment by OzanKurt** [comment]
Done some fixed.
Would be awesome to head feedback.

https://github.com/OzanKurt/Repoist/pull/21

**Comment by mattsims** [comment]
I can confirm this is now fixed, thank you! 👍
